import fs from 'node:fs';
import path from 'node:path';

type Json = Record<string, unknown>;
const ROOT = path.resolve(__dirname, '..');
const META_KEYS = new Set(['header', 'subheader', 'headerLayout', 'headerPosition', 'headerLink']);

function isImage(o: unknown): o is Json {
  return !!o && typeof o === 'object' && 'originalUrl' in (o as Json) && 'dimensions' in (o as Json);
}
// Some paths in the crawl are percent-encoded twice; decoding twice restores
// them (paths here never contain a literal '%').
function toSrc(originalUrl: string): string {
  let p = originalUrl;
  try { p = decodeURIComponent(p); } catch { /* keep */ }
  try { p = decodeURIComponent(p); } catch { /* keep */ }
  return '/images/' + p.replace(/^\/?fileadmin\/user_upload\//, '').replace(/^\/?fileadmin\//, '');
}
function toVideoSrc(originalUrl: string): string {
  let p = originalUrl;
  try { p = decodeURIComponent(p); } catch { /* keep */ }
  return '/videos/' + path.posix.basename(p);
}
function cropOf(img: Json, key: string) {
  const crop = (img.crop as Json | undefined)?.[key] as Json | undefined;
  const area = (crop?.cropArea as Json | undefined) ?? { x: 0, y: 0, width: 1, height: 1 };
  return { x: Number(area.x), y: Number(area.y), width: Number(area.width), height: Number(area.height) };
}
function convert(o: unknown): unknown {
  if (Array.isArray(o)) return o.map(convert);
  if (o && typeof o === 'object') {
    if (isImage(o)) {
      const mime = String(o.mime ?? '');
      if (mime.startsWith('video/')) return { src: toVideoSrc(String(o.originalUrl)), mime };
      const dims = o.dimensions as Json;
      return {
        src: toSrc(String(o.originalUrl)), width: Number(dims.width), height: Number(dims.height),
        alt: (o.alt as string) ?? '', title: (o.title as string | null) ?? null, mime,
        crop: { default: cropOf(o, 'default'), mobile: cropOf(o, 'mobile') },
      };
    }
    const out: Json = {};
    for (const [k, v] of Object.entries(o as Json)) out[k] = convert(v);
    return out;
  }
  return o;
}
function convertSection(e: Json) {
  const content = e.content as Json;
  const cleaned: Json = {};
  for (const [k, v] of Object.entries(content)) if (!META_KEYS.has(k) && k !== 'type') cleaned[k] = v;
  return { id: Number(e.id), type: String(e.type), appearance: e.appearance, content: convert(cleaned) };
}
function convertMeta(m: Json) {
  const img = (x: unknown) => (isImage(x) ? convert(x) : null);
  return {
    title: m.title ?? '', description: m.description ?? '', ogTitle: m.ogTitle ?? '', ogDescription: m.ogDescription ?? '',
    ogImage: img(m.ogImage), twitterTitle: m.twitterTitle ?? '', twitterDescription: m.twitterDescription ?? '',
    twitterImage: img(m.twitterImage), twitterCard: m.twitterCard ?? 'summary',
    robots: (m.robots as Json) ?? { noIndex: false, noFollow: false },
  };
}
export function generate(slug: string, exportName: string) {
  const src = path.join(ROOT, 'docs/reference/pages', slug === 'home' ? 'en.json' : `en__${slug}.json`);
  const page = JSON.parse(fs.readFileSync(src, 'utf8')) as Json;
  const columns: Json = {};
  for (const [col, els] of Object.entries(page.content as Json)) columns[col] = (els as Json[]).map(convertSection);
  const out = {
    id: Number(page.id), slug: String(page.slug), backendLayout: String((page.appearance as Json).backendLayout),
    meta: convertMeta(page.meta as Json), columns,
  };
  const file = path.join(ROOT, 'content/en', `${slug}.ts`);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file,
    `// GENERATED by scripts/gen-content.ts from docs/reference/pages/${path.basename(src)}. Do not edit by hand.\n` +
    `import type { PageContent } from '@/lib/content';\n\nexport const ${exportName}: PageContent = ${JSON.stringify(out, null, 2)};\n`);
  console.log('wrote', path.relative(ROOT, file));
}
const [slug = 'home', name = 'home'] = process.argv.slice(2);
generate(slug, name);
