import type { PageContent } from '@/lib/content';

export const about: PageContent = {
  id: 9058,
  slug: '/about/',
  backendLayout: 'defaultLayout',
  meta: {
    title: 'About Leonaara - Our Founders & Philosophy',
    description: 'Meet the founders behind Leonaara, Ravikanth Reddy Busam, Rajashekhar Reddy, Avinash Reddy and Srinivas Reddy, and the philosophy of trust, quality and lasting value guiding every project.',
    ogTitle: 'About Leonaara',
    ogDescription: 'Meet the founders behind Leonaara, Ravikanth Reddy Busam, Rajashekhar Reddy, Avinash Reddy and Srinivas Reddy, and the philosophy of trust, quality and lasting value guiding every project.',
    ogImage: null,
    twitterTitle: 'About Leonaara',
    twitterDescription: 'Meet the founders behind Leonaara, Ravikanth Reddy Busam, Rajashekhar Reddy, Avinash Reddy and Srinivas Reddy, and the philosophy of trust, quality and lasting value guiding every project.',
    twitterImage: null,
    twitterCard: 'summary',
    robots: { noIndex: false, noFollow: false },
  },
  columns: {
    colPos0: [
      // text: placeholder lorem ipsum per the user's request, filling the
      // hero's left column (Hero.tsx's onlyText textCls, grid-column:1/span_4)
      // -- the mountain photo visible to the right at this scroll position
      // belongs to the next section down (id 287's imgright), not this hero,
      // so no image/layout change was needed here.
      { id: 235, type: 'mask_hero', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { herolayout: 'only-text', title: '', titleh2: '', titleimg: '', text: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Leonaara sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', img: [], sideimg: [], imgsummer: [], sideimgsummer: [] } },
      { id: 287, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: '<i>Ravikanth Reddy Busam</i>', text: '<p><b>(Founder & CEO)</b></p><p>Some build structures. A rare few build belief. Ravikanth Reddy Busam belongs to the latter. With 25+ years across finance, technology, and real estate, his journey has been guided by one belief, lasting value is built on integrity.<br/>From founding a global technology venture in 2008 to shaping 1M+ sq. ft. of development, serving 560+ homeowners, and creating ₹1000+ crores in value, his work reflects discipline, precision, and trust.</p>', imgleft: [{ src: '/images/leonaara-about-courtyard.jpg', width: 3200, height: 1793, mime: 'image/jpeg', title: null, alt: 'Sunlit courtyard with an open wooden shutter window on a whitewashed wall, framed by tree branches and a rustic outdoor dining table', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/leonaara-about-courtyard.jpg', width: 3200, height: 1793, mime: 'image/jpeg', title: null, alt: 'Sunlit courtyard with an open wooden shutter window on a whitewashed wall, framed by tree branches and a rustic outdoor dining table', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [{ src: '/images/leonaara-about-courtyard.jpg', width: 3200, height: 1793, mime: 'image/jpeg', title: null, alt: 'Sunlit courtyard with an open wooden shutter window on a whitewashed wall, framed by tree branches and a rustic outdoor dining table', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgrightsummer: [{ src: '/images/leonaara-about-courtyard.jpg', width: 3200, height: 1793, mime: 'image/jpeg', title: null, alt: 'Sunlit courtyard with an open wooden shutter window on a whitewashed wall, framed by tree branches and a rustic outdoor dining table', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
      { id: 290, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: '<i>Rajashekhar Reddy</i>', text: '<p><b>(Executive Director - Engineering)</b></p><p>With a strong foundation in engineering and execution, Rajashekhar Reddy brings strategic expertise and technical excellence to Leonaara as Executive Director (Engineering).</p>', imgleft: [{ src: '/images/leonaara-about-courtyard.jpg', width: 3200, height: 1793, mime: 'image/jpeg', title: null, alt: 'Sunlit courtyard with an open wooden shutter window on a whitewashed wall, framed by tree branches and a rustic outdoor dining table', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/leonaara-about-courtyard.jpg', width: 3200, height: 1793, mime: 'image/jpeg', title: null, alt: 'Sunlit courtyard with an open wooden shutter window on a whitewashed wall, framed by tree branches and a rustic outdoor dining table', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [{ src: '/images/leonaara-about-courtyard.jpg', width: 3200, height: 1793, mime: 'image/jpeg', title: null, alt: 'Sunlit courtyard with an open wooden shutter window on a whitewashed wall, framed by tree branches and a rustic outdoor dining table', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgrightsummer: [{ src: '/images/leonaara-about-courtyard.jpg', width: 3200, height: 1793, mime: 'image/jpeg', title: null, alt: 'Sunlit courtyard with an open wooden shutter window on a whitewashed wall, framed by tree branches and a rustic outdoor dining table', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
      { id: 292, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: '<i>Avinash Reddy</i>', text: '<p><b>(Executive Director – Strategy & Customer Relations)</b></p><p>As Executive Director (Strategy & Customer Relations), Avinash Reddy brings a strong focus on strategic growth, customer experience, and long-term relationships.&nbsp;</p>\n<p>With a vision centered on trust and excellence, he ensures every interaction reflects Leonaara’s commitment to transparency, thoughtful service, and creating meaningful experiences for homeowners.</p>', imgleft: [{ src: '/images/leonaara-about-courtyard.jpg', width: 3200, height: 1793, mime: 'image/jpeg', title: null, alt: 'Sunlit courtyard with an open wooden shutter window on a whitewashed wall, framed by tree branches and a rustic outdoor dining table', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/leonaara-about-courtyard.jpg', width: 3200, height: 1793, mime: 'image/jpeg', title: null, alt: 'Sunlit courtyard with an open wooden shutter window on a whitewashed wall, framed by tree branches and a rustic outdoor dining table', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [{ src: '/images/leonaara-about-courtyard.jpg', width: 3200, height: 1793, mime: 'image/jpeg', title: null, alt: 'Sunlit courtyard with an open wooden shutter window on a whitewashed wall, framed by tree branches and a rustic outdoor dining table', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgrightsummer: [{ src: '/images/leonaara-about-courtyard.jpg', width: 3200, height: 1793, mime: 'image/jpeg', title: null, alt: 'Sunlit courtyard with an open wooden shutter window on a whitewashed wall, framed by tree branches and a rustic outdoor dining table', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
      { id: 546, type: 'mask_img', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { img: [{ src: '/images/leonaara-about-courtyard.jpg', width: 3200, height: 1793, mime: 'image/jpeg', title: null, alt: 'Sunlit courtyard with an open wooden shutter window on a whitewashed wall, framed by tree branches and a rustic outdoor dining table', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgsummer: [] } },
      { id: 295, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: '<i>Srinivas Reddy</i>', text: '<p><b>(Executive Director – Projects & Liaisoning)</b></p><p>Srinivas Reddy leads Projects & Liaisoning at Leonaara with a focus on seamless execution, strategic coordination, and timely delivery. </p><p>His expertise ensures every project moves forward with precision, compliance, and excellence.</p>', imgleft: [{ src: '/images/leonaara-about-courtyard.jpg', width: 3200, height: 1793, mime: 'image/jpeg', title: null, alt: 'Sunlit courtyard with an open wooden shutter window on a whitewashed wall, framed by tree branches and a rustic outdoor dining table', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/leonaara-about-courtyard.jpg', width: 3200, height: 1793, mime: 'image/jpeg', title: null, alt: 'Sunlit courtyard with an open wooden shutter window on a whitewashed wall, framed by tree branches and a rustic outdoor dining table', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [], imgrightsummer: [] } },
      { id: 300, type: 'mask_video', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { video: [], videosummer: [] } },
    ],
  },
};
