import type { PageContent } from '@/lib/content';

export const about: PageContent = {
  id: 9058,
  slug: '/about/',
  backendLayout: 'defaultLayout',
  meta: {
    title: 'Experience moments of grounding and relaxation at the Leonaara Spa',
    description: 'Dive into the silence of eriro Spa. Inspired by nature, you experience a wellness retreat for body and soul amidst the mountain world, drawing from the wisdom of the ancients.',
    ogTitle: 'Spa',
    ogDescription: 'Dive into the silence of eriro Spa. Inspired by nature, you experience a wellness retreat for body and soul amidst the mountain world, drawing from the wisdom of the ancients.',
    ogImage: null,
    twitterTitle: 'Spa',
    twitterDescription: 'Dive into the silence of eriro Spa. Inspired by nature, you experience a wellness retreat for body and soul amidst the mountain world, drawing from the wisdom of the ancients.',
    twitterImage: null,
    twitterCard: 'summary',
    robots: { noIndex: false, noFollow: false },
  },
  columns: {
    colPos0: [
      { id: 235, type: 'mask_hero', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { herolayout: 'only-text', title: '', titleh2: '', titleimg: '', text: '', img: [], sideimg: [], imgsummer: [], sideimgsummer: [] } },
      { id: 287, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: '<i>Ravikanth Reddy Busam</i>', text: '<p><b>(Founder & CEO)</b></p><p>Some build structures. A rare few build belief. Ravikanth Reddy Busam belongs to the latter. With 25+ years across finance, technology, and real estate, his journey has been guided by one belief, lasting value is built on integrity.<br/>From founding a global technology venture in 2008 to shaping 1M+ sq. ft. of development, serving 560+ homeowners, and creating ₹1000+ crores in value, his work reflects discipline, precision, and trust.</p>', imgleft: [{ src: '/images/SPA/AlexMoling_Eriro_Wellness-37.jpg', width: 5464, height: 8192, mime: 'image/jpeg', title: null, alt: '', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/Suiten/himil/AlexMoling_Eriro_Winter-first-14.jpg', width: 3000, height: 2001, mime: 'image/jpeg', title: null, alt: '', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [{ src: '/images/Best-Of_Alex_Moling/AlexMoling_Eriro_Wellness-3.jpg', width: 8190, height: 5463, mime: 'image/jpeg', title: null, alt: '', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgrightsummer: [{ src: '/images/Hendrik_Stüwe/Pool_Shooting_2605_10.jpg', width: 2800, height: 1868, mime: 'image/jpeg', title: null, alt: '', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
      { id: 304, type: 'mask_video', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { video: [{ src: '/videos/eriro_alpinehide_schwimmen2.MOV', mime: 'video/quicktime' }], videosummer: [] } },
      { id: 290, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: '<i>Rajashekhar Reddy</i>', text: '<p><b>(Executive Director - Engineering)</b></p><p>With a strong foundation in engineering and execution, Rajashekhar Reddy brings strategic expertise and technical excellence to Leonaara as Executive Director (Engineering).</p>', imgleft: [{ src: '/images/eriro-ehrwald-alpinehide-spa-07.jpg', width: 1200, height: 950, mime: 'image/jpeg', title: null, alt: 'Handcrafted infusion bucket before backlit live edge and reclaimed wood sauna wall – traditional sauna ritual at eriro Alpine Hide Ehrwald', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/unikateur_Bilder/Winter/AlexMoling_Eriro_Wellness-75.jpg', width: 8192, height: 5464, mime: 'image/jpeg', title: null, alt: 'Woman in bathrobe with cup at window of eriro Alpine Hide gazing at snow-covered winter landscape with mountain panorama near Zugspitze', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [{ src: '/images/eriro-ehrwald-alpinehide-spa-07.jpg', width: 1200, height: 950, mime: 'image/jpeg', title: null, alt: 'Handcrafted infusion bucket before backlit live edge and reclaimed wood sauna wall – traditional sauna ritual at eriro Alpine Hide Ehrwald', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgrightsummer: [{ src: '/images/eriro-ehrwald-alpinehide-spa-02.jpg', width: 1500, height: 1350, mime: 'image/jpeg', title: null, alt: 'Spruce sauna at eriro with natural stone dry walls, wooden bucket and panorama glazing to Wetterstein alpine slopes with Kneipp plunge pool on wood deck', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
      { id: 292, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: '<i>Avinash Reddy</i>', text: '<p><b>(Executive Director – Strategy & Customer Relations)</b></p><p>As Executive Director (Strategy & Customer Relations), Avinash Reddy brings a strong focus on strategic growth, customer experience, and long-term relationships.&nbsp;</p>\n<p>With a vision centered on trust and excellence, he ensures every interaction reflects Leonaara’s commitment to transparency, thoughtful service, and creating meaningful experiences for homeowners.</p>', imgleft: [{ src: '/images/eriro-ehrwald-alpinehide-spa-08.jpg', width: 1200, height: 950, mime: 'image/jpeg', title: null, alt: 'Rustic spa area at eriro Alpine Hide with natural stone walls, sauna and warm light – alpine mountain silhouettes merging with wellness refuge', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/unikateur_Bilder/Winter/AlexMoling_Eriro_Wellness-62.jpg', width: 7765, height: 5176, mime: 'image/jpeg', title: null, alt: 'Panoramic view through large window with natural stone frame and wooden lattice onto snow-covered mountain peak and conifer forest at eriro Alpine Hide Ehrwald', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [{ src: '/images/eriro-ehrwald-alpinehide-spa-08.jpg', width: 1200, height: 950, mime: 'image/jpeg', title: null, alt: 'Rustic spa area at eriro Alpine Hide with natural stone walls, sauna and warm light – alpine mountain silhouettes merging with wellness refuge', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgrightsummer: [{ src: '/images/Best-Of_Alex_Moling/AlexMoling_Eriro_Wellness-6.jpg', width: 8192, height: 5464, mime: 'image/jpeg', title: null, alt: 'Vertical window in eriro spa framing Wetterstein summits above spruce forest, dark plunge pool mirroring mountain light in hand-plastered ochre clay wall', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
      { id: 546, type: 'mask_img', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { img: [{ src: '/images/Eriro_Spa_ehrwalder-alm_oesterreich_wellness-01.jpg', width: 2560, height: 1440, mime: 'image/jpeg', title: null, alt: 'Meditative spa room at eriro with branch wood ribbed ceiling, clay walls, boulder, spruce bed and hand-woven cotton hammocks in sun-dappled light', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgsummer: [] } },
      { id: 295, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: '<i>Srinivas Reddy</i>', text: '<p><b>(Executive Director – Projects & Liaisoning)</b></p><p>Srinivas Reddy leads Projects & Liaisoning at Leonaara with a focus on seamless execution, strategic coordination, and timely delivery. </p><p>His expertise ensures every project moves forward with precision, compliance, and excellence.</p>', imgleft: [{ src: '/images/eriro-ehrwald-alpinehide-spa-09.jpg', width: 1200, height: 950, mime: 'image/jpeg', title: null, alt: 'Meditation cushion of natural fabric on cork mat in sunlight – mindful silence and inner reflection at eriro Alpine Hide retreat', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-ehrwald-alpinehide-spa-04.jpg', width: 1500, height: 1350, mime: 'image/jpeg', title: null, alt: 'Woman in profile holding brass-colored singing bowl with mallet before misty mountain backdrop with conifer forest', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [], imgrightsummer: [] } },
      { id: 300, type: 'mask_video', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { video: [], videosummer: [] } },
    ],
  },
};
