import type { PageContent } from '@/lib/content';

export const alpineHide: PageContent = {
  id: 58,
  slug: '/alpine-hide/',
  backendLayout: 'defaultLayout',
  meta: {
    title: 'Alpine Hide – a return to the origin at 1,550 m',
    description: "Discover eriro, the smallest Alpine Hide at 1,550 m in Austria's Tyrol. A place of regeneration and silence, making real mountain life experienceable in its simplicity. Hotel opening in July 2024.",
    ogTitle: 'Alpine Hide',
    ogDescription: "Discover eriro, the smallest Alpine Hide at 1,550 m in Austria's Tyrol. A place of regeneration and silence, making real mountain life experienceable in its simplicity. Hotel opening in July 2024.",
    ogImage: null,
    twitterTitle: 'Alpine Hide',
    twitterDescription: "Discover eriro, the smallest Alpine Hide at 1,550 m in Austria's Tyrol. A place of regeneration and silence, making real mountain life experienceable in its simplicity. Hotel opening in July 2024.",
    twitterImage: null,
    twitterCard: 'summary',
    robots: { noIndex: false, noFollow: false },
  },
  columns: {
    colPos0: [
      { id: 81, type: 'mask_hero', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { herolayout: 'subpage', title: 'rooted in the beginnings<br>\r\nof everything<br>\r\n', titleh2: 'Back to the <br>\r\nessentials', titleimg: '', text: '', img: [{ src: '/images/unikateur_Bilder/Winter/AlexMoling_Eriro_Rooms-89.jpg', width: 8192, height: 5464, mime: 'image/jpeg', title: null, alt: 'Attic suite with reclaimed wood paneling, sofa and balcony with view of snow-covered mountain summits and winter forest at Zugspitze', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], sideimg: [{ src: '/images/eriro-ehrwald-oesterreich-alpine-hide-01.jpg', width: 1200, height: 1600, mime: 'image/jpeg', title: null, alt: 'Man in wool jacket carrying armful of snow-covered spruce wood, striped cotton shirt, weathered hands, winter atmosphere at eriro Ehrwald', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgsummer: [{ src: '/images/eriro-alpine-hide-oesterreich-ehrwald-luxus-02.jpg', width: 1920, height: 1480, mime: 'image/jpeg', title: null, alt: 'Loft sleeping area at eriro beneath recycled rafters with linen bed, open balcony with woven daybed and view across Wetterstein layers', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], sideimgsummer: [{ src: '/images/unikateur_Bilder/eriro_alpinehide_frosch.jpg', width: 2560, height: 3838, mime: 'image/jpeg', title: null, alt: 'Tiny young toad sitting on gently opened palm in sunlight – golden bracelet, alpine nature discovery during eriro summer retreat', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
      { id: 117, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: 'Back to<br>\r\nbeginnings<br>\r\nall of being', text: '<p>Drift away from everyday life, embark on a journey into yourself, to your origins, to the essentials: As the smallest, most secluded hideaway in the Alps, at an elevation of 1,550 metres, eriro is a place of regeneration and tranquillity. A place where you can experience the true, authentic way of life on the mountain – in all its simplicity and pristine nature, and even more so in its innate understanding of how little it takes to be happy.&nbsp;</p>', imgleft: [{ src: '/images/eriro-ehrwald-alpine-hide-luxus-natur-05.jpg', width: 1200, height: 950, mime: 'image/jpeg', title: null, alt: 'Quiet infinity spa pool with reclaimed wood dividers and linen lounger – luxurious wellness area at eriro Alpine Hide Ehrwald', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/unikateur_Bilder/Winter/eriro_alpinehide_feuer.jpg', width: 2560, height: 3838, mime: 'image/jpeg', title: null, alt: 'Hand placing rough birch log into crackling campfire at Wetterstein – orange flames, glowing embers and sparks before snow-covered ground', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [], imgrightsummer: [{ src: '/images/eriro-ehrwald-spa-alpinehide-suite-04.jpg', width: 1500, height: 1350, mime: 'image/jpeg', title: null, alt: 'Guest at mirror-smooth mountain lake with perfect reflection of snow-covered Wetterstein summits and spruces, contemplative immersion in eriro nature realm', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
      { id: 82, type: 'mask_quote', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { quote: '<p>"eriro invites you to leave everything that is familiar to you behind and experience the mountain in its archaic natural state ..."</p>', autor: 'Your hosts at eriro', img: [{ src: '/images/unikateur_Bilder/eriro_alpinehide_handstein.jpg', width: 2560, height: 3838, mime: 'image/jpeg', title: null, alt: 'Hand with black ring touching rough Wetterstein limestone rock at Ehrwald – tactile nature connection at eriro Alpine Hide near Zugspitze', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
      { id: 543, type: 'mask_img', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { img: [{ src: '/images/unikateur_Bilder/Winter/AlexMoling_Eriro_Hall-35.jpg', width: 7942, height: 5297, mime: 'image/jpeg', title: null, alt: 'Spacious hall at eriro Alpine Hide with natural stone floor, long stone table and panorama windows onto snow-covered winter forest at Zugspitze', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgsummer: [{ src: '/images/eriro-alpine-hide-oesterreich-ehrwald-luxus-13.jpg', width: 2560, height: 1440, mime: 'image/jpeg', title: null, alt: 'Solid wood table with books beneath round log ceiling, tripod spotting scope on balcony, golden evening light over spruce forest slopes and Wetterstein peaks at eriro', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
      { id: 157, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: 'Captivating <br>\r\nas the <br>\r\norigins', text: '<p>The eriro Alpine hideaway’s architectural design pays homage to the aesthetic of Alpine ecosystem structural elements, with emphasis on simplicity and traditions of craftsmanship. The interior features a minimalist design that focusses on the essentials. Lovingly handcrafted local materials including wood, wool and loden create an ambience that provides structure and shelter and, just as it did thousands of years ago, protects against the reliably present untamed forces of mountain nature.</p>', imgleft: [{ src: '/images/eriro-ehrwald-alpine-hide-luxus-natur-06.jpg', width: 1200, height: 950, mime: 'image/jpeg', title: null, alt: 'Hand-forged pendant light in mountain silhouette before reclaimed wood lattice wall – design detail at eriro Alpine Hide near Zugspitze', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-ehrwald-spa-alpinehide-suite-05.jpg', width: 1500, height: 1350, mime: 'image/jpeg', title: null, alt: 'Motion blur of woman between massive spruce columns and clay walls with hanging stone installations at eriro Alpine Hide Ehrwald', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [], imgrightsummer: [] } },
      {
        id: 158,
        type: 'mask_accordions',
        appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' },
        content: {
          title: '',
          text: '',
          accordion: [
            { uid: '20', title: 'Responsibility towards the region', info: '', text: '<p>The cornerstone and starting point for the realisation of eriro was the responsibility towards the region – to create a look with the Alpine hideaway that pays homage to the area’s traditional architecture and the beauty of its historic structures.</p>', linktext: '', link: '' },
            { uid: '21', title: 'Alpine region aesthetics', info: '', text: '<p>The eriro project seeks to capture the beauty of the simple and traditional. Three typical Alpine saddle roofs – a symbol of the collaboration between the founders – join together in a way that resonates warmth and protection, and open towards the sky at the bend.&nbsp;</p>', linktext: '', link: '' },
            { uid: '22', title: 'A tribute to the origins ', info: '', text: '<p>The concept of eriro is fuelled by the central tenet of recognising and honouring the importance of origins in all aspects: original Alpine region construction, original knowledge of the properties of plants, such as tanning agents for treating wood, or original need to provide shelter from wind and weather with the right kind of structure.</p>', linktext: '', link: '' },
            { uid: '23', title: 'Unparalled in time-honoured craftsmanship', info: '', text: '<p>No CNC machines were used for any of the work. The architectural elements are almost exclusively crafted by hand, such as the 4,000 cotter pins, or the long, handcrafted table in the lobby. Each lamp is made by hand. The interior is embellished with woven, bound and carved wood, pure sheep’s wool carpets, and handmade coat hangers by designer huanzn. Even the bathtubs are crafted by hand out of tree trunks and sealed with resin.&nbsp;</p>', linktext: '', link: '' },
            { uid: '24', title: 'The value of local materials', info: '', text: '<p>In line with the idea of origins, almost all materials are locally sourced. Wood from the surrounding forests is the foundation for all interior materials from floor to ceiling. Architectural detail elements are manufactured and processed in Ehrwald. The roof is shingled with larch from the nearby forests. The wood darkens, a deliberate transformation and finishing that keeps with the Alpine aesthetic.</p>', linktext: '', link: '' },
          ],
        },
      },
      { id: 200, type: 'mask_video', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { video: [], videosummer: [] } },
      {
        id: 160,
        type: 'mask_accordions',
        appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' },
        content: {
          title: 'Sustainability',
          text: '',
          accordion: [
            { uid: '25', title: 'A sense for the essentials', info: '', text: "<p>The vastness of the pristine landscape at 1,550 m awakens an innermost humility in the face of nature’s magnificence: all life follows its rhythm. The seasons and their changing weather shape everyday life. The distinctive essence of this place determines its values:</p><ul><li>step back to the essentials</li><li>create something new with utmost care</li><li>protect nature and the place so many call home&nbsp;</li><li>create awareness for the region's assets: people, animals, culture</li></ul>", linktext: '', link: '' },
            { uid: '26', title: 'Nature as a core element', info: '', text: "<p>Natural resources of the region can be found in all aspects that make up eriro, hand in hand with the desire and commitment to live each day in respect of and with nature.</p><ul><li><span>The architecture leans toward stylistically Alpine. Natural, local materials compose the exterior and interior: Stone and reclaimed wood, sheep's wool and loden&nbsp;</span></li><li><span>Mountain experiences focus on local culture, are aligned with the weather and seasons, and hone the senses for interacting with nature</span></li><li><span>The kitchen sources most products from the Alpine region and favours shortest-distance delivery routes</span></li><li><span>Organic waste is recycled on site, returning it back to nature</span></li></ul>", linktext: '', link: '' },
          ],
        },
      },
      {
        id: 178,
        type: 'mask_teaserslider',
        appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' },
        content: {
          teaserslides: [
            { uid: '15', title: 'Mountain pleasures', imgleft: [{ src: '/images/eriro-alpine-hide-ehrwald-berggenuss-01.jpg', width: 1200, height: 1400, mime: 'image/jpeg', title: null, alt: 'Artful gourmet dish on stone plate at eriro Alpine Hide – edible alpine flowers, herbs and golden chips as homage to alpine terroir cuisine', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-alpine-hide-ehrwald-berggenuss-02.jpg', width: 1500, height: 1660, mime: 'image/jpeg', title: null, alt: 'Golden broth being poured from ceramic pitcher over mushrooms and elderflowers – intimate gourmet ritual in handcrafted bowl at eriro Alpine Hide', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], infotext: 'Weather on a plate in its many forms', linktext: 'Flavour of mountain origins', link: { href: '/culinary/', target: null, class: null, title: null, linkText: 't3://page?uid=61', additionalAttributes: [] } },
            { uid: '16', title: 'Step back to the origins', imgleft: [{ src: '/images/eriro-alpine-hide-ehrwald-rueckkehr-ursprung-01.jpg', width: 1200, height: 1400, mime: 'image/jpeg', title: null, alt: 'Wooden balcony of eriro Alpine Hide in warm evening light with view of rugged rock summits and dense conifer forest – pure alpine majesty', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-alpine-hide-ehrwald-rueckkehr-ursprung-02.jpg', width: 1500, height: 1660, mime: 'image/jpeg', title: null, alt: 'Light-flooded living area with massive wooden table, telescope and panoramic view of green alpine forests – quiet luxury moments at eriro Alpine Hide', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], infotext: 'Touch what time has left untouched', linktext: 'To the Alpine Hide', link: { href: '/origin/', target: null, class: null, title: null, linkText: 't3://page?uid=86', additionalAttributes: [] } },
            { uid: '19', title: 'Nature as a habitat', imgleft: [{ src: '/images/eriro-alpine-hide-ehrwald-natur-lebensraum-01.jpg', width: 1200, height: 1400, mime: 'image/jpeg', title: null, alt: 'Cozy moment in wool socks with coffee cup and photo book at natural stone fireplace – comforting sanctuary at eriro Alpine Hide', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-alpine-hide-ehrwald-natur-lebensraum-02.jpg', width: 1500, height: 1660, mime: 'image/jpeg', title: null, alt: 'Handcrafted wool patchwork wall with chess set in sunlit living area – alpine craftsmanship meets design at eriro Alpine Hide', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], infotext: 'At one with nature and the mountain', linktext: 'Structure and shelter: the suites', link: { href: '/suites/boum/', target: null, class: null, title: null, linkText: 't3://page?uid=44', additionalAttributes: [] } },
          ],
        },
      },
    ],
  },
};
