import type { PageContent } from '@/lib/content';

export const culinary: PageContent = {
  id: 61,
  slug: '/culinary/',
  backendLayout: 'defaultLayout',
  meta: {
    title: 'The taste of origin cuisine',
    description: "Experience nature-connected delights at eriro. Immerse yourself in the world of primal cuisine and savor the culinary diversity of the mountain nature's seasons with every dish.",
    ogTitle: 'Culinary',
    ogDescription: "Experience nature-connected delights at eriro. Immerse yourself in the world of primal cuisine and savor the culinary diversity of the mountain nature's seasons with every dish.",
    ogImage: null,
    twitterTitle: 'Culinary',
    twitterDescription: "Experience nature-connected delights at eriro. Immerse yourself in the world of primal cuisine and savor the culinary diversity of the mountain nature's seasons with every dish.",
    twitterImage: null,
    twitterCard: 'summary',
    robots: { noIndex: false, noFollow: false },
  },
  columns: {
    colPos0: [
      { id: 164, type: 'mask_hero', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { herolayout: 'subpage', title: 'A taste of nature', titleh2: 'The flavour<br>\r\nof mountain <br>\r\norigins', titleimg: '', text: '', img: [{ src: '/images/eriro-alpine-hide-oesterreich-ehrwald-luxus-07.jpg', width: 1920, height: 1480, mime: 'image/jpeg', title: null, alt: 'Alpine fine-dining at eriro: Tartare on split bone marrow with mushroom carpaccio, nasturtium, egg yolk dots and wildflowers on moss base', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], sideimg: [{ src: '/images/eriro-ehrwald-alpinehide-kulinarik-03.jpg', width: 1200, height: 1600, mime: 'image/jpeg', title: null, alt: 'Tyrolean spinach dumplings with sage butter foam in hand-thrown gradient ceramic bowl on light spruce wood table, eriro alpine cuisine', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgsummer: [], sideimgsummer: [] } },
      { id: 166, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: 'Wind and weather <br>\r\non a plate', text: '<p>A cuisine of the origins, founded on preparation methods inspired by Alpine tradition and local ingredients. The focus is a new, exciting interpretation of treasured and familiar flavours. Menus embody the ever-changing weather conditions of the mountain in both taste and appearance: rough, rugged and powerful, or gentle, mild and delicate, the dishes are a reflection of the seasons and untamed forces of mountain nature.&nbsp;</p>', imgleft: [{ src: '/images/unikateur_Bilder/Food/eriro_alpinehide_ei.jpg', width: 2560, height: 3838, mime: 'image/jpeg', title: null, alt: 'Half eggshell with luminous yolk on hay in wooden bowl – dramatic light celebrating rustic authenticity of eriro gourmet cuisine', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-ehrwald-alpinehide-kulinarik-02.jpg', width: 1500, height: 1350, mime: 'image/jpeg', title: null, alt: 'Tattooed hand pouring clear golden broth from matte black ceramic pitcher over chanterelles and elderflowers in stoneware bowl, eriro alpine cuisine', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [], imgrightsummer: [] } },
      { id: 544, type: 'mask_img', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { img: [{ src: '/images/eriro-alpine-hide-oesterreich-ehrwald-luxus-15.jpg', width: 2560, height: 1440, mime: 'image/jpeg', title: null, alt: 'Eriro fine-dining with curved spruce wood bench, wool cushion, linen napkin and hand-thrown ceramic in warm evening light', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgsummer: [] } },
      { id: 170, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: 'A real <i>"fuir"</i><br>\r\nheats the stove', text: '<p>The way food has been cooked in the Alps for as long as anyone can remember. The <i>fuir</i> (local dialect for ‘fire’) of the restaurant’s open grill pays homage to the original way of life in the Alps. Impressive presentations on wood or stone, on grain or in the form of a nest, offer a multi-sensory culinary experience of the mountains through taste, smell, and visual aesthetic.</p>', imgleft: [{ src: '/images/eriro-ehrwald-alpinehide-kulinarik-05.jpg', width: 1200, height: 950, mime: 'image/jpeg', title: null, alt: 'Hand placing fine crystal wine glass on rustic reclaimed wood table in sunlight – dinner preparation at eriro Alpine Hide Ehrwald', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-ehrwald-spa-alpinehide-suite-09.jpg', width: 1500, height: 1350, mime: 'image/jpeg', title: null, alt: 'Smoking lamb chops on spruce branch bed in dark ceramic, rising aromatic smoke on rough reclaimed wood table in eriro restaurant Ehrwald', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [], imgrightsummer: [] } },
      { id: 167, type: 'mask_img', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { img: [{ src: '/images/unikateur_Bilder/Winter/AlexMoling_Eriro_Restaurant-26.jpg', width: 8192, height: 5464, mime: 'image/jpeg', title: null, alt: 'Restaurant area at eriro Alpine Hide with set wooden table, wine glasses and terrace view onto snow-covered Zugspitze mountain panorama', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgsummer: [{ src: '/images/Eriro_Restaurant_ehrwalder-alm_oesterreich_genuss-01.jpg', width: 2560, height: 1440, mime: 'image/jpeg', title: null, alt: 'Set fine-dining table of spruce wood with wine goblets and driftwood sculptures, golden evening sun over Wetterstein panorama in eriro restaurant', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
      {
        id: 211,
        type: 'mask_teaserslider',
        appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' },
        content: {
          teaserslides: [
            { uid: '55', title: 'Nature in harmony', imgleft: [{ src: '/images/eriro-alpine-hide-ehrwald-natur-harmonie-01.jpg', width: 1200, height: 1400, mime: 'image/jpeg', title: null, alt: 'Handcrafted Pssst door sign of wood and natural stone on textured wool carpet – loving detail at eriro Alpine Hide hideaway', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-alpine-hide-ehrwald-natur-harmonie-02.jpg', width: 1500, height: 1660, mime: 'image/jpeg', title: null, alt: 'Woman in black dress walking through sunny clearing between spruces and mountain silhouettes – mindful nature connection at eriro Alpine Hide', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], infotext: 'Step back to the beginnings of everything', linktext: 'How eriro came to be', link: { href: '/alpine-hide/', target: null, class: null, title: null, linkText: 't3://page?uid=58', additionalAttributes: [] } },
            { uid: '51', title: 'Ochi Kema', imgleft: [{ src: '/images/unikateur_Bilder/eriro_alpinehide_rückentropfen.jpg', width: 2560, height: 1707, mime: 'image/jpeg', title: null, alt: 'Water droplets and goosebumps on sun-tanned shoulder after bathing – braided hair with grass blade, sensual eriro mountain lake experience', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/Hendrik_Stüwe/_R8A5800.jpg', width: 2800, height: 1868, mime: 'image/jpeg', title: null, alt: '', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], infotext: 'Basking in nature and stillness', linktext: 'Profound revitalization in the spa', link: { href: '/spa/', target: null, class: null, title: null, linkText: 't3://page?uid=108', additionalAttributes: [] } },
            { uid: '54', title: 'Come face to face with the untouched', imgleft: [{ src: '/images/eriro-alpine-hide-ehrwald-unerlebtes-erleben-01.jpg', width: 1200, height: 1400, mime: 'image/jpeg', title: null, alt: "Strong hands holding soft, natural sheep's wool – authentic craftsmanship and alpine materiality as soul of eriro Alpine Hide", crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-alpine-hide-ehrwald-unerlebtes-erleben-02.jpg', width: 1500, height: 1660, mime: 'image/jpeg', title: null, alt: 'Couple hand in hand in sunlit mountain forest with golden lens flare – romantic togetherness around eriro Alpine Hide', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], infotext: 'Purely Alpine', linktext: 'Nature and culture experiences of the mountain', link: { href: '/experiences/', target: null, class: null, title: null, linkText: 't3://page?uid=60', additionalAttributes: [] } },
          ],
        },
      },
    ],
  },
};
