import type { PageContent } from '@/lib/content';
import { experiencesHero, experiencesFilter } from '@/content/en/experiencesShared';

export const leiba: PageContent = {
  id: 97,
  slug: '/leiba/',
  backendLayout: '11',
  meta: {
    title: "leiba - experience original life on the mountain", description: "leiba in the eriro: experience how life on the mountain has been shaped for generations - with wood stone & water a life with nature.", ogTitle: "LEIBA", ogDescription: "leiba in the eriro: experience how life on the mountain has been shaped for generations - with wood stone & water a life with nature.", ogImage: null,
    twitterTitle: "LEIBA", twitterDescription: "leiba in the eriro: experience how life on the mountain has been shaped for generations - with wood stone & water a life with nature.", twitterImage: null, twitterCard: 'summary',
    robots: { noIndex: false, noFollow: false },
  },
  columns: {
    colPos0: [experiencesHero, experiencesFilter],
    colPos5: [
  { id: 192, type: 'mask_hero', appearance: { layout: "default", frameClass: "default", spaceBefore: "", spaceAfter: "" }, content: { herolayout: "subpage", title: "Life in the mountains", titleh2: "Authentic <br>\r\nmountain <br>\r\nexperience", titleimg: "", text: "", img: [{ src: "/images/eriro-alpine-hide-oesterreich-ehrwald-luxus-03.jpg", width: 1920, height: 1480, mime: "image/jpeg", title: null, alt: "Guest in winter clothing splitting spruce wood with axe on snow-covered chopping block, split logs in snow before eriro Alpine Hide Ehrwald", crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], sideimg: [{ src: "/images/eriro-ehrwald-oesterreich-alpine-hide-02.jpg", width: 1200, height: 1600, mime: "image/jpeg", title: null, alt: "Person in mustard cardigan gazing from behind toward mist-shrouded Wetterstein wall, mountain pine foreground at eriro", crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgsummer: [{ src: "/images/unikateur_Bilder/eriro_alpinehide_holz.jpg", width: 2560, height: 3838, mime: "image/jpeg", title: null, alt: "Authentic craftsmanship: Splitting firewood with traditional axe on weathered tree stump in evening light, eriro Alpine Hide Ehrwald", crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], sideimgsummer: [{ src: "/images/unikateur_Bilder/DR1A9915.jpg", width: 8192, height: 5464, mime: "image/jpeg", title: null, alt: "Guest in mustard knit sweater gazing reverently at monumental alpine rock wall – contemplative silence in high mountains at eriro Alpine Hide", crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
  { id: 193, type: 'mask_imgtext', appearance: { layout: "default", frameClass: "default", spaceBefore: "", spaceAfter: "" }, content: { title: "Leiba", text: "<p>For millions of years, nature has shaped all life as it exists today on the mountain. In the Alps, humans have adapted to the sudden changes of wind and weather and the challenges that each season brings. Living on the mountain requires skill and the use of all the senses: collecting wood from the surrounding forests and preparing it for the winter, clearing the house and farm from drifts after stormy snowfalls, working with stone, wood and other materials from the mountains. Collecting water directly from the mountain spring and feeling it on your skin. These are activities that become anchored in one’s memory because they ensure survival on the mountain by working together.&nbsp;</p>", imgleft: [{ src: "/images/unikateur_Bilder/Winter/eriro_alpinehide_scheitel2.jpg", width: 2560, height: 3838, mime: "image/jpeg", title: null, alt: "Strong hand gripping freshly split spruce logs with visible annual rings before cream linen shirt – honest craftsmanship in mountain winter", crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: "/images/eriro-ehrwald-spa-alpinehide-suite-06.jpg", width: 1500, height: 1350, mime: "image/jpeg", title: null, alt: "Blonde hair in wind before dark winter spruce forest, person in wool coat from behind, snow-covered mountain backdrop at eriro Ehrwald", crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [], imgrightsummer: [] } },
    ],
  },
};
