import type { PageContent } from '@/lib/content';

export const origin: PageContent = {
  id: 86,
  slug: '/origin/',
  backendLayout: 'defaultLayout',
  meta: {
    title: 'Leonaara – a journey back to the origin',
    description: 'Experience the authentic and genuine alpine life at a place of retreat and originality in the Tyrolean Alps. A hotel opening in July 2024 in Austria.',
    ogTitle: 'Origin',
    ogDescription: 'Experience the authentic and genuine alpine life at a place of retreat and originality in the Tyrolean Alps. A hotel opening in July 2024 in Austria.',
    ogImage: null,
    twitterTitle: 'Origin',
    twitterDescription: 'Experience the authentic and genuine alpine life at a place of retreat and originality in the Tyrolean Alps. A hotel opening in July 2024 in Austria.',
    twitterImage: null,
    twitterCard: 'summary',
    robots: { noIndex: false, noFollow: false },
  },
  columns: {
    colPos0: [
      { id: 141, type: 'mask_hero', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { herolayout: 'subpage', title: 'Endless<br>\r\nsummer days<br>\r\n', titleh2: "Here's to a carefree way of life", titleimg: '', text: '', img: [{ src: '/images/unikateur_Bilder/Winter/AlexMoling_Eriro_Exterior-57.jpg', width: 8192, height: 5464, mime: 'image/jpeg', title: null, alt: 'Winter exterior view of eriro Alpine Hide with wooden facade, natural stone wall, wooden balcony and snow-covered conifer before mountain panorama', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], sideimg: [{ src: '/images/eriro-ehrwald-oesterreich-alpine-hide-07.jpg', width: 1200, height: 1600, mime: 'image/jpeg', title: null, alt: 'Hand gently stroking gray donkey fur in golden evening light on alpine meadow, tender animal-human encounter in eriro nature realm', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgsummer: [{ src: '/images/eriro-alpine-hide-oesterreich-ehrwald-luxus-08.jpg', width: 1920, height: 1480, mime: 'image/jpeg', title: null, alt: 'Larch wood terrace deck of eriro with rattan chairs, rustic fence and view of spruce forest slopes before Wetterstein peak in morning haze', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], sideimgsummer: [{ src: '/images/eriro-ehrwald-oesterreich-alpine-hide-07.jpg', width: 1200, height: 1600, mime: 'image/jpeg', title: null, alt: 'Hand gently stroking gray donkey fur in golden evening light on alpine meadow, tender animal-human encounter in eriro nature realm', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
      { id: 143, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: 'Happiness lies in simplicity', text: '<p>How easily one can find happiness. Beyond the wealth of the tangible and intangible lies a place surrounded by pristine nature, one that touches you with its simplicity: like the feeling of soft, forest-scented moss under your feet, or marvelling at the unique crystalline forms of snowflakes, like the feeling of being completely grounded.&nbsp;In this very moment. In happiness.</p>', imgleft: [{ src: '/images/eriro-ehrwald-alpine-hide-luxus-natur-07.jpg', width: 1200, height: 950, mime: 'image/jpeg', title: null, alt: 'Cozy wool socks on rustic wooden steps – alpine sanctuary and handcrafted comfort at eriro Alpine Hide hideaway', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/unikateur_Bilder/eriro_alpinehide_rinde.jpg', width: 2560, height: 1708, mime: 'image/jpeg', title: null, alt: 'Woman hiding her face behind rough tree bark in Wetterstein sunlight – playful wildness and golden jewelry at eriro Alpine Hide', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [], imgrightsummer: [] } },
      { id: 182, type: 'mask_video', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { video: [{ src: '/videos/eriro_alpinehide_luft.mp4', mime: 'video/mp4' }], videosummer: [] } },
      {
        id: 145,
        type: 'mask_accordions',
        appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' },
        content: {
          title: 'The owners',
          text: '',
          accordion: [
            { uid: '5', title: 'The Posch family - the visionaries', info: '', text: '<p>‘We had a vision: of a journey to rediscover ourselves, to acknowledge and take a step towards the positive feeling that arises out of a sense of freedom and vitality. With the courage and the willingness to challenge the boundaries of our comfort zones, we wanted to create a place where origins, simplicity and the archaic take centre stage and utterly captivate. A space for unique experiences and new, inspiring adventures that fill our guests with pride and happiness that they can take home.’ Dominik and Amelie Posch</p>', linktext: '', link: '' },
            { uid: '6', title: 'The Spielmann family - the strategists', info: '', text: '<p>‘As strategic, financial and process consultants, we provided our expertise to overcome the hurdles of realising this special and remote project in the midst of nature. This unique setting on the Ehrwalder Alm Alpine pasture is both a challenge and an opportunity to, with the company of great partners, redefine Alpine tourism and offer a way of living that bring people back their origins and roots.’&nbsp; Martin and Christina Spielmann</p>', linktext: '', link: '' },
            { uid: '7', title: 'Andreas Mader - the constructor', info: '', text: '<p>‘As a timber construction and carpentry specialist, this was a unique opportunity to create a showcase project for sustainable tourism at a former company site, surrounded by nature, and to realise it together with partners that can contribute hotel industry expertise. We created a destination out of original, local materials that offers a glimpse into real, original forest living in the Alps. A place where you want to stay.’ Andreas Mader</p>', linktext: '', link: '' },
          ],
        },
      },
      { id: 183, type: 'mask_img', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { img: [{ src: '/images/unikateur_Bilder/Winter/AlexMoling_Eriro_Hall-40.jpg', width: 8027, height: 5354, mime: 'image/jpeg', title: null, alt: 'Two sheepskin armchairs with rustic wooden table before panorama window with view of snow-covered winter landscape at eriro Alpine Hide Ehrwald', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgsummer: [{ src: '/images/Eriro_Spa_ehrwalder-alm_oesterreich_wellness-02.jpg', width: 2560, height: 1440, mime: 'image/jpeg', title: null, alt: 'Hewn plank ceiling lounge at eriro with sheepskin armchairs, rope cross window frames and full glazing to Ehrwald alpine meadows and spruce forest', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
      { id: 147, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: 'Just as it was thousands of years ago', text: "<p>Memories of days without a care in the world, hearts energised by untamed lightness and boundless freedom: the love for this tiny corner of the planet pulsates in rhythm with an appreciation for life, where every moment lived becomes a precious moment experienced with all the senses – as elemental as nature passing through the seasons, as constant as the mountain with its millions of years of age. Here's to a carefree way of life!</p>", imgleft: [{ src: '/images/eriro-ehrwald-alpine-hide-luxus-natur-08.jpg', width: 1200, height: 950, mime: 'image/jpeg', title: null, alt: 'Glass of red wine before crackling fireplace at eriro Alpine Hide – golden light, alpine coziness and luxurious moment of indulgence in evening', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-ehrwald-spa-alpinehide-suite-10.jpg', width: 1500, height: 1350, mime: 'image/jpeg', title: null, alt: 'Wetterstein limestone walls with scree slope and low-hanging clouds, golden evening light on larch-spruce fringe at eriro Ehrwald', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [], imgrightsummer: [] } },
      {
        id: 215,
        type: 'mask_teaserslider',
        appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' },
        content: {
          teaserslides: [
            { uid: '58', title: 'Mountain pleasures', imgleft: [{ src: '/images/eriro-alpine-hide-ehrwald-berggenuss-01.jpg', width: 1200, height: 1400, mime: 'image/jpeg', title: null, alt: 'Artful gourmet dish on stone plate at eriro Alpine Hide – edible alpine flowers, herbs and golden chips as homage to alpine terroir cuisine', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-alpine-hide-ehrwald-berggenuss-02.jpg', width: 1500, height: 1660, mime: 'image/jpeg', title: null, alt: 'Golden broth being poured from ceramic pitcher over mushrooms and elderflowers – intimate gourmet ritual in handcrafted bowl at eriro Alpine Hide', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], infotext: 'Weather on a plate in its many forms', linktext: 'Flavour of mountain origins ', link: { href: '/culinary/', target: null, class: null, title: null, linkText: 't3://page?uid=61', additionalAttributes: [] } },
            { uid: '60', title: 'Touch the untouched', imgleft: [{ src: '/images/eriro-alpine-hide-ehrwald-unerlebtes-erleben-01.jpg', width: 1200, height: 1400, mime: 'image/jpeg', title: null, alt: "Strong hands holding soft, natural sheep's wool – authentic craftsmanship and alpine materiality as soul of eriro Alpine Hide", crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-alpine-hide-ehrwald-unerlebtes-erleben-02.jpg', width: 1500, height: 1660, mime: 'image/jpeg', title: null, alt: 'Couple hand in hand in sunlit mountain forest with golden lens flare – romantic togetherness around eriro Alpine Hide', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], infotext: 'Purely Alpine', linktext: 'Nature and culture experiences of the mountain', link: { href: '/experiences/', target: null, class: null, title: null, linkText: 't3://page?uid=60', additionalAttributes: [] } },
            { uid: '62', title: 'Nature as a habitat', imgleft: [{ src: '/images/eriro-alpine-hide-ehrwald-natur-lebensraum-01.jpg', width: 1200, height: 1400, mime: 'image/jpeg', title: null, alt: 'Cozy moment in wool socks with coffee cup and photo book at natural stone fireplace – comforting sanctuary at eriro Alpine Hide', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-alpine-hide-ehrwald-natur-lebensraum-02.jpg', width: 1500, height: 1660, mime: 'image/jpeg', title: null, alt: 'Handcrafted wool patchwork wall with chess set in sunlit living area – alpine craftsmanship meets design at eriro Alpine Hide', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], infotext: 'At one with nature and the mountain', linktext: 'Structure and shelter: the suites', link: { href: '/suites/boum/', target: null, class: null, title: null, linkText: 't3://page?uid=44', additionalAttributes: [] } },
          ],
        },
      },
    ],
  },
};
