import type { PageContent } from '@/lib/content';

export const spa: PageContent = {
  id: 108,
  slug: '/spa/',
  backendLayout: 'defaultLayout',
  meta: {
    title: 'Experience moments of grounding and relaxation at the eriro Spa',
    description: 'Dive into the silence of eriro Spa. Inspired by nature, you experience a wellness retreat for body and soul amidst the mountain world, drawing from the wisdom of the ancients.',
    ogTitle: 'Spa',
    ogDescription: 'Dive into the silence of eriro Spa. Inspired by nature, you experience a wellness retreat for body and soul amidst the mountain world, drawing from the wisdom of the ancients.',
    ogImage: null,
    twitterTitle: 'Spa',
    twitterDescription: 'Dive into the silence of eriro Spa. Inspired by nature, you experience a wellness retreat for body and soul amidst the mountain world, drawing from the wisdom of the ancients.',
    twitterImage: null,
    twitterCard: 'summary',
    robots: { noIndex: false, noFollow: false },
  },
  columns: {
    colPos0: [
      { id: 235, type: 'mask_hero', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { herolayout: 'only-text', title: 'The sounds of nature echo on skin', titleh2: 'Silence as an<br>\r\nexperience', titleimg: '', text: '<p><i>Ochi kema</i> – come back to your inner self. Become grounded by rooting yourself in nature. The fine scent of herbs and hay on a summer’s walk, the ethereal, earthy smell of autumn, the energising power of ice-cold mountain water: inspired by traditional wisdom of local herbalists and naturalists, the spa taps into nature’s diversity to bring the collective power of Alpine origins into a space of tranquillity.</p>', img: [], sideimg: [], imgsummer: [], sideimgsummer: [] } },
      { id: 287, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: '<i>wazzar:</i> <br>\r\nCalming waters', text: '<p>Water is the source of all life. The eriro pools offer a relaxing and intimate setting where time feels as if it is simply standing still, and where one can explore the inner self. It is water that creates this ambience, containing the very essence of both stillness and vitality. As water flows and swirls, it moves energising properties with it that carry and redistribute a wealth of information. With this in mind, each of the four pools serve their own special purpose.</p>', imgleft: [{ src: '/images/SPA/AlexMoling_Eriro_Wellness-37.jpg', width: 5464, height: 8192, mime: 'image/jpeg', title: null, alt: '', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/Suiten/himil/AlexMoling_Eriro_Winter-first-14.jpg', width: 3000, height: 2001, mime: 'image/jpeg', title: null, alt: '', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [{ src: '/images/Best-Of_Alex_Moling/AlexMoling_Eriro_Wellness-3.jpg', width: 8190, height: 5463, mime: 'image/jpeg', title: null, alt: '', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgrightsummer: [{ src: '/images/Hendrik_Stüwe/Pool_Shooting_2605_10.jpg', width: 2800, height: 1868, mime: 'image/jpeg', title: null, alt: '', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
      {
        id: 288,
        type: 'mask_accordions',
        appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' },
        content: {
          title: 'Pools',
          text: '',
          accordion: [
            { uid: '121', title: 'Alba', info: '', text: '<p>Beneath the open sky, the new alpine meadow infinity pool opens to the landscape. In the warm water, mountain air, light and vastness become tangible. A bath between stillness, sky and the quiet interplay of the mountains. Water warmed to 32°C carries the body calmly and evenly, at eye level with the meadows. The gaze drifts into the panorama of the majestic peaks of the Tyrolean Alps.</p>', linktext: '', link: '' },
            { uid: '46', title: 'Sela', info: '', text: "<p>The space created by darkness is transformed into a haven for the mind to wander. The meditation pool is located underground, bathed in an inviting and soothingly dimmed light. The 36-degree water cradles the body like a soft silken blanket. There is a singing bowl on the ceiling whose reflection of indirect light evokes thoughts of the sun.</p><ul><li><span>the narrow, low entrance resembles the entrance to a cave&nbsp;</span></li><li>the singing bowl can be played by pulling on a rope</li><li>the brass bowl produces sound waves that sends vibrations through the water</li><li>the water's vibrations are transformed into sound as you submerge yourself below the surface</li><li>in this soothing and inviting softly lit space, time seems to stop, making way for your imagination to run free</li></ul>", linktext: '', link: '' },
            { uid: '47', title: 'Taja', info: '', text: '<p>Beside the 40-degree pool is a small window with a magnificent view of the Tajakopf mountain. Hot water bathing provides deep relaxation and boosts overall well-being. It improves blood circulation in the skin and releases muscle tension. This bathing technique is inspired by the Japanese onsen bathing culture.</p>', linktext: '', link: '' },
            { uid: '48', title: 'Sunna', info: '', text: '<p>An observation platform of sorts, towering above the valley, the Panorama Pool offers a 360-degree view of the majestic Tyrolean Alp peaks through floor-to-ceiling windows. Within this enclosed space sits a 36-degree bath, positioned in a corner for the perfectly private experience.</p>', linktext: '', link: '' },
          ],
        },
      },
      { id: 304, type: 'mask_video', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { video: [{ src: '/images/unikateur_Video/eriro_alpinehide_schwimmen2.MOV', mime: 'video/quicktime' }], videosummer: [] } },
      { id: 289, type: 'mask_break', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: 'Nature <br>\r\non the <br>\r\nskin', imgleft: [{ src: '/images/eriro-ehrwald-alpinehide-spa-10.jpg', width: 1500, height: 1250, mime: 'image/jpeg', title: null, alt: 'Natural stone massage in spa of eriro Alpine Hide – healing touch with alpine mineral stones for deep grounding and physical wellbeing', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [], imgright: [{ src: '/images/eriro-ehrwald-alpinehide-spa-06.jpg', width: 1200, height: 950, mime: 'image/jpeg', title: null, alt: 'Golden singing bowl with wooden mallet on white towel before natural wood wall – sound therapy in spa of eriro Alpine Hide Ehrwald', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgrightsummer: [] } },
      { id: 290, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: '<i>wermi:</i> <br>\r\nThe warmth <br>\r\nof the forest', text: '<p>Daily life on the mountain is defined by contrasts: sun, rain and snow can be seen replacing one after the other in a matter of minutes. Spruce and Finnish saunas give the body the warmth it needs on cold winter days.</p>\n<p>Water access is just a few steps from the sauna. Follow the sheltered path to the end – surrounded by stones on both sides – and arrive to a waterfall rock shower. The spa area extends along the ground level and out towards the Alpine meadows. An additional outdoor terrace with lounge chairs is a perfect spot for relaxing after a sauna session.</p>', imgleft: [{ src: '/images/eriro-ehrwald-alpinehide-spa-07.jpg', width: 1200, height: 950, mime: 'image/jpeg', title: null, alt: 'Handcrafted infusion bucket before backlit live edge and reclaimed wood sauna wall – traditional sauna ritual at eriro Alpine Hide Ehrwald', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/unikateur_Bilder/Winter/AlexMoling_Eriro_Wellness-75.jpg', width: 8192, height: 5464, mime: 'image/jpeg', title: null, alt: 'Woman in bathrobe with cup at window of eriro Alpine Hide gazing at snow-covered winter landscape with mountain panorama near Zugspitze', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [{ src: '/images/eriro-ehrwald-alpinehide-spa-07.jpg', width: 1200, height: 950, mime: 'image/jpeg', title: null, alt: 'Handcrafted infusion bucket before backlit live edge and reclaimed wood sauna wall – traditional sauna ritual at eriro Alpine Hide Ehrwald', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgrightsummer: [{ src: '/images/eriro-ehrwald-alpinehide-spa-02.jpg', width: 1500, height: 1350, mime: 'image/jpeg', title: null, alt: 'Spruce sauna at eriro with natural stone dry walls, wooden bucket and panorama glazing to Wetterstein alpine slopes with Kneipp plunge pool on wood deck', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
      {
        id: 291,
        type: 'mask_accordions',
        appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' },
        content: {
          title: 'Sauna',
          text: '',
          accordion: [
            { uid: '49', title: 'Fiuhta', info: '', text: '<p>The organic spruce sauna sits adjacent to a window that offers an unobstructed view of the Alpine pastures and mountains. The sauna is equipped with wood storage. The aesthetic and scent make you feel as if you are in the middle of a mountain forest.</p><ul><li><span>60 degrees</span></li><li><span>infusions</span></li><li>self-applied peel treatments</li></ul>', linktext: '', link: '' },
            { uid: '50', title: 'Steinaz', info: '', text: '<p>Access to the Finnish sauna is via a stone path. The staggered slabs sit above the surface of ankle-high water, so that the path to the sauna can either be made by balancing on dry stones or walking through the water.&nbsp;</p><ul><li><span>90 degrees</span></li><li><span>infusions&nbsp;</span></li><li><span>self-applied peel treatments</span></li></ul>', linktext: '', link: '' },
          ],
        },
      },
      { id: 292, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: '<i>roa:</i> <br>\r\nSound of silence', text: '<p>The spa area was intentionally positioned on the building’s lower level, where it could open onto an outdoor terrace flush with the surrounding terrain. An invitation to connect with Earth’s elements, with your own origins, your own nature, with untamed rocks, forests and meadows of the Tyrolean mountain pastures. The spa floor is uneven, resembling a field path made up of tiny round stones, encouraging you to explore stone, rock and earth barefoot, rediscovering another dimension of sensory experience through touching and feeling.&nbsp;</p>', imgleft: [{ src: '/images/eriro-ehrwald-alpinehide-spa-08.jpg', width: 1200, height: 950, mime: 'image/jpeg', title: null, alt: 'Rustic spa area at eriro Alpine Hide with natural stone walls, sauna and warm light – alpine mountain silhouettes merging with wellness refuge', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/unikateur_Bilder/Winter/AlexMoling_Eriro_Wellness-62.jpg', width: 7765, height: 5176, mime: 'image/jpeg', title: null, alt: 'Panoramic view through large window with natural stone frame and wooden lattice onto snow-covered mountain peak and conifer forest at eriro Alpine Hide Ehrwald', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [{ src: '/images/eriro-ehrwald-alpinehide-spa-08.jpg', width: 1200, height: 950, mime: 'image/jpeg', title: null, alt: 'Rustic spa area at eriro Alpine Hide with natural stone walls, sauna and warm light – alpine mountain silhouettes merging with wellness refuge', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgrightsummer: [{ src: '/images/Best-Of_Alex_Moling/AlexMoling_Eriro_Wellness-6.jpg', width: 8192, height: 5464, mime: 'image/jpeg', title: null, alt: 'Vertical window in eriro spa framing Wetterstein summits above spruce forest, dark plunge pool mirroring mountain light in hand-plastered ochre clay wall', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }] } },
      {
        id: 293,
        type: 'mask_accordions',
        appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' },
        content: {
          title: 'Relaxation and sound room',
          text: '',
          accordion: [
            { uid: '51', title: 'Roa', info: '', text: '<p>The spa’s relaxation area is integrated into the 209 m2 pool and sauna premises, featuring 4 lounge chairs and room for 10 people. After a session in the sauna, sound room, or a dip in one of the pools, come here to experience tranquillity as it blends with the natural elements of the Alps.&nbsp;</p>', linktext: '', link: '' },
            { uid: '52', title: 'Hewi', info: '', text: "<p>In the dim lighting of a secluded, sunlight-devoid space at the rear of the spa is a sound room where time is invited to stand still. Sound allows for complete concentration on oneself and full harmonisation of body and mind.&nbsp;</p><ul><li>straw creates a protective nest that surrounds the room's two loungers&nbsp;</li><li>the loungers' singing bowls radiate music that surrounds the body</li><li>selected music resonates throughout the room and across the body like a massage of sound waves</li><li>the sound waves correspond to the frequency at which Earth pulsates - 7.83 Hertz - also known as the Schumann resonance</li><li>this promotes awareness and relaxation of the body&nbsp;</li><li>a nature film plays on the room's screen, accompanying the music</li></ul>", linktext: '', link: '' },
          ],
        },
      },
      { id: 546, type: 'mask_img', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { img: [{ src: '/images/Eriro_Spa_ehrwalder-alm_oesterreich_wellness-01.jpg', width: 2560, height: 1440, mime: 'image/jpeg', title: null, alt: 'Meditative spa room at eriro with branch wood ribbed ceiling, clay walls, boulder, spruce bed and hand-woven cotton hammocks in sun-dappled light', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgsummer: [] } },
      { id: 295, type: 'mask_imgtext', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { title: '<i>lebenti:</i> <br>\r\nRelaxation rituals under the sun and stars', text: '<p>After a challenging hike or a long day of skiing, your muscles long for rest and relaxation. Book a private massage in the <i>lebenti</i> treatment room, located under the protective gabled roof on eriro’s top floor. After your treatment, take a moment to step out onto the small balcony of the <i>lebenti</i> and take in the magnificent view of the Wetterstein massif.</p>', imgleft: [{ src: '/images/eriro-ehrwald-alpinehide-spa-09.jpg', width: 1200, height: 950, mime: 'image/jpeg', title: null, alt: 'Meditation cushion of natural fabric on cork mat in sunlight – mindful silence and inner reflection at eriro Alpine Hide retreat', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-ehrwald-alpinehide-spa-04.jpg', width: 1500, height: 1350, mime: 'image/jpeg', title: null, alt: 'Woman in profile holding brass-colored singing bowl with mallet before misty mountain backdrop with conifer forest', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgleftsummer: [], imgrightsummer: [] } },
      { id: 300, type: 'mask_video', appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' }, content: { video: [], videosummer: [] } },
      {
        id: 233,
        type: 'mask_teaserslider',
        appearance: { layout: 'default', frameClass: 'default', spaceBefore: '', spaceAfter: '' },
        content: {
          teaserslides: [
            { uid: '65', title: 'Step back to the origins', imgleft: [{ src: '/images/eriro-alpine-hide-ehrwald-rueckkehr-ursprung-01.jpg', width: 1200, height: 1400, mime: 'image/jpeg', title: null, alt: 'Wooden balcony of eriro Alpine Hide in warm evening light with view of rugged rock summits and dense conifer forest – pure alpine majesty', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-alpine-hide-ehrwald-rueckkehr-ursprung-02.jpg', width: 1500, height: 1660, mime: 'image/jpeg', title: null, alt: 'Light-flooded living area with massive wooden table, telescope and panoramic view of green alpine forests – quiet luxury moments at eriro Alpine Hide', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], infotext: 'Touch what time has left untouched', linktext: 'To the Alpine Hide', link: { href: '/en/origin/', target: null, class: null, title: null, linkText: 't3://page?uid=86', additionalAttributes: [] } },
            { uid: '66', title: 'Touch the untouched', imgleft: [{ src: '/images/eriro-alpine-hide-ehrwald-unerlebtes-erleben-01.jpg', width: 1200, height: 1400, mime: 'image/jpeg', title: null, alt: "Strong hands holding soft, natural sheep's wool – authentic craftsmanship and alpine materiality as soul of eriro Alpine Hide", crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-alpine-hide-ehrwald-unerlebtes-erleben-02.jpg', width: 1500, height: 1660, mime: 'image/jpeg', title: null, alt: 'Couple hand in hand in sunlit mountain forest with golden lens flare – romantic togetherness around eriro Alpine Hide', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], infotext: 'Purely Alpine', linktext: 'Nature and culture experiences of the mountain', link: { href: '/en/experiences/', target: null, class: null, title: null, linkText: 't3://page?uid=60', additionalAttributes: [] } },
            { uid: '68', title: 'Nature as a habitat', imgleft: [{ src: '/images/eriro-alpine-hide-ehrwald-natur-lebensraum-01.jpg', width: 1200, height: 1400, mime: 'image/jpeg', title: null, alt: 'Cozy moment in wool socks with coffee cup and photo book at natural stone fireplace – comforting sanctuary at eriro Alpine Hide', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], imgright: [{ src: '/images/eriro-alpine-hide-ehrwald-natur-lebensraum-02.jpg', width: 1500, height: 1660, mime: 'image/jpeg', title: null, alt: 'Handcrafted wool patchwork wall with chess set in sunlit living area – alpine craftsmanship meets design at eriro Alpine Hide', crop: { default: { x: 0, y: 0, width: 1, height: 1 }, mobile: { x: 0, y: 0, width: 1, height: 1 } } }], infotext: 'At one with nature and the mountain', linktext: 'Structure and shelter: the suites', link: { href: '/en/suites/boum/', target: null, class: null, title: null, linkText: 't3://page?uid=44', additionalAttributes: [] } },
          ],
        },
      },
    ],
  },
};
